/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Sphereon.SDK.Classification.Client;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing JobApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class JobApiTests
    {
        private JobApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new JobApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' JobApi
            //Assert.IsInstanceOfType(typeof(JobApi), instance, "instance is a JobApi");
        }

        
        /// <summary>
        /// Test AddProjectId
        /// </summary>
        [Test]
        public void AddProjectIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //string projectId = null;
            //var response = instance.AddProjectId(jobId, projectId);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test CreateClassificationJob
        /// </summary>
        [Test]
        public void CreateClassificationJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ClassificationSettings classificationSettings = null;
            //var response = instance.CreateClassificationJob(classificationSettings);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test DeleteJob
        /// </summary>
        [Test]
        public void DeleteJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.DeleteJob(jobId);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test GetClassificationResult
        /// </summary>
        [Test]
        public void GetClassificationResultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.GetClassificationResult(jobId);
            //Assert.IsInstanceOf<ClassificationResponse> (response, "response is ClassificationResponse");
        }
        
        /// <summary>
        /// Test GetJobWithClaimParameters
        /// </summary>
        [Test]
        public void GetJobWithClaimParametersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.GetJobWithClaimParameters(jobId);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test GetJobs
        /// </summary>
        [Test]
        public void GetJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> status = null;
            //var response = instance.GetJobs(status);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test SubmitJob
        /// </summary>
        [Test]
        public void SubmitJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.SubmitJob(jobId);
            //Assert.IsInstanceOf<ClassificationJobResponse> (response, "response is ClassificationJobResponse");
        }
        
        /// <summary>
        /// Test UploadInputFile
        /// </summary>
        [Test]
        public void UploadInputFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //System.IO.Stream stream = null;
            //var response = instance.UploadInputFile(jobId, stream);
            //Assert.IsInstanceOf<StreamResponse> (response, "response is StreamResponse");
        }
        
    }

}
