/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.classification);
  }
}(this, function(expect, classification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new classification.ClassificationProjectResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClassificationProjectResult', function() {
    it('should create an instance of ClassificationProjectResult', function() {
      // uncomment below and update the code to test ClassificationProjectResult
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be.a(classification.ClassificationProjectResult);
    });

    it('should have the property projectInfo (base name: "projectInfo")', function() {
      // uncomment below and update the code to test the property projectInfo
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be();
    });

    it('should have the property inline (base name: "inline")', function() {
      // uncomment below and update the code to test the property inline
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be();
    });

    it('should have the property stream (base name: "stream")', function() {
      // uncomment below and update the code to test the property stream
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be();
    });

    it('should have the property classificationType (base name: "classificationType")', function() {
      // uncomment below and update the code to test the property classificationType
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be();
    });

    it('should have the property resultType (base name: "resultType")', function() {
      // uncomment below and update the code to test the property resultType
      //var instane = new classification.ClassificationProjectResult();
      //expect(instance).to.be();
    });

  });

}));
