/**
 * Classification API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.classification);
  }
}(this, function(expect, classification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new classification.ClassificationSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClassificationSettings', function() {
    it('should create an instance of ClassificationSettings', function() {
      // uncomment below and update the code to test ClassificationSettings
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be.a(classification.ClassificationSettings);
    });

    it('should have the property lifecycle (base name: "lifecycle")', function() {
      // uncomment below and update the code to test the property lifecycle
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property classificationTypes (base name: "classificationTypes")', function() {
      // uncomment below and update the code to test the property classificationTypes
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property maxResults (base name: "maxResults")', function() {
      // uncomment below and update the code to test the property maxResults
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property detailLevels (base name: "detailLevels")', function() {
      // uncomment below and update the code to test the property detailLevels
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property inputStorageLocation (base name: "inputStorageLocation")', function() {
      // uncomment below and update the code to test the property inputStorageLocation
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property resultStorageLocation (base name: "resultStorageLocation")', function() {
      // uncomment below and update the code to test the property resultStorageLocation
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property resultTypes (base name: "resultTypes")', function() {
      // uncomment below and update the code to test the property resultTypes
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property classificationType (base name: "classificationType")', function() {
      // uncomment below and update the code to test the property classificationType
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

    it('should have the property ocrMode (base name: "ocrMode")', function() {
      // uncomment below and update the code to test the property ocrMode
      //var instane = new classification.ClassificationSettings();
      //expect(instance).to.be();
    });

  });

}));
