/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.classification);
  }
}(this, function(expect, classification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new classification.ProjectClassificationTextLine();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectClassificationTextLine', function() {
    it('should create an instance of ProjectClassificationTextLine', function() {
      // uncomment below and update the code to test ProjectClassificationTextLine
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be.a(classification.ProjectClassificationTextLine);
    });

    it('should have the property top (base name: "top")', function() {
      // uncomment below and update the code to test the property top
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property left (base name: "left")', function() {
      // uncomment below and update the code to test the property left
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property bottom (base name: "bottom")', function() {
      // uncomment below and update the code to test the property bottom
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property words (base name: "words")', function() {
      // uncomment below and update the code to test the property words
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property right (base name: "right")', function() {
      // uncomment below and update the code to test the property right
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new classification.ProjectClassificationTextLine();
      //expect(instance).to.be();
    });

  });

}));
