/**
 * Classification API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClassificationSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ClassificationJob = factory(root.classification.ApiClient, root.classification.ClassificationSettings);
  }
}(this, function(ApiClient, ClassificationSettings) {
  'use strict';




  /**
   * The ClassificationJob model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJob
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ClassificationJob</code>.
   * The classification job. Has access to the job settings.
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJob
   * @class
   * @param jobId {String} The server generated job jobId. This jobId is checked against the jobId in the request path on overy invocation
   */
  var exports = function(jobId) {
    var _this = this;

    _this['jobId'] = jobId;


  };

  /**
   * Constructs a <code>ClassificationJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJob} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJob} The populated <code>ClassificationJob</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('jobId')) {
        obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
      }
      if (data.hasOwnProperty('settings')) {
        obj['settings'] = ClassificationSettings.constructFromObject(data['settings']);
      }
      if (data.hasOwnProperty('targetProjectIds')) {
        obj['targetProjectIds'] = ApiClient.convertToType(data['targetProjectIds'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The server generated job jobId. This jobId is checked against the jobId in the request path on overy invocation
   * @member {String} jobId
   */
  exports.prototype['jobId'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationSettings} settings
   */
  exports.prototype['settings'] = undefined;
  /**
   * @member {Array.<String>} targetProjectIds
   */
  exports.prototype['targetProjectIds'] = undefined;



  return exports;
}));


