/**
 * Classification API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Stream'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Inline'), require('./Stream'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ClassificationProjectResult = factory(root.classification.ApiClient, root.classification.Inline, root.classification.Stream);
  }
}(this, function(ApiClient, Inline, Stream) {
  'use strict';




  /**
   * The ClassificationProjectResult model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ClassificationProjectResult</code>.
   * The result from document classification
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ClassificationProjectResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult} The populated <code>ClassificationProjectResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('inline')) {
        obj['inline'] = Inline.constructFromObject(data['inline']);
      }
      if (data.hasOwnProperty('stream')) {
        obj['stream'] = Stream.constructFromObject(data['stream']);
      }
      if (data.hasOwnProperty('classificationType')) {
        obj['classificationType'] = ApiClient.convertToType(data['classificationType'], 'String');
      }
      if (data.hasOwnProperty('projectId')) {
        obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
      }
      if (data.hasOwnProperty('resultType')) {
        obj['resultType'] = ApiClient.convertToType(data['resultType'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Storage of classification result in response
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline} inline
   */
  exports.prototype['inline'] = undefined;
  /**
   * External storage of classification result
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Stream} stream
   */
  exports.prototype['stream'] = undefined;
  /**
   * Classification type
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult.ClassificationTypeEnum} classificationType
   */
  exports.prototype['classificationType'] = undefined;
  /**
   * Project id
   * @member {String} projectId
   */
  exports.prototype['projectId'] = undefined;
  /**
   * Returned result in response and/or store
   * @member {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationProjectResult.ResultTypeEnum>} resultType
   */
  exports.prototype['resultType'] = undefined;


  /**
   * Allowed values for the <code>classificationType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ClassificationTypeEnum = {
    /**
     * value: "DOCUMENT"
     * @const
     */
    "DOCUMENT": "DOCUMENT",
    /**
     * value: "PAGES"
     * @const
     */
    "PAGES": "PAGES",
    /**
     * value: "DOCUMENT_SEPARATION"
     * @const
     */
    "DOCUMENT_SEPARATION": "DOCUMENT_SEPARATION"  };

  /**
   * Allowed values for the <code>resultType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ResultTypeEnum = {
    /**
     * value: "INLINE"
     * @const
     */
    "INLINE": "INLINE",
    /**
     * value: "STORAGE"
     * @const
     */
    "STORAGE": "STORAGE"  };


  return exports;
}));


