/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResultItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClassificationResultItem'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ClassificationResult = factory(root.classification.ApiClient, root.classification.ClassificationResultItem);
  }
}(this, function(ApiClient, ClassificationResultItem) {
  'use strict';




  /**
   * The ClassificationResult model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResult
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ClassificationResult</code>.
   * The classification result
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResult
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ClassificationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResult} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResult} The populated <code>ClassificationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [ClassificationResultItem]);
      }
    }
    return obj;
  }

  /**
   * A list of the classification results.
   * @member {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationResultItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


