/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationInputInfo', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/JobInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClassificationInputInfo'), require('./JobInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ClassificationJobResponse = factory(root.classification.ApiClient, root.classification.ClassificationInputInfo, root.classification.JobInfo);
  }
}(this, function(ApiClient, ClassificationInputInfo, JobInfo) {
  'use strict';




  /**
   * The ClassificationJobResponse model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJobResponse
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ClassificationJobResponse</code>.
   * The classification job. Has access to the job settings as well as ocr engine tasks
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJobResponse
   * @class
   * @param inputInfo {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationInputInfo} Original input information
   * @param jobInfo {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/JobInfo} Job info
   */
  var exports = function(inputInfo, jobInfo) {
    var _this = this;

    _this['inputInfo'] = inputInfo;
    _this['jobInfo'] = jobInfo;
  };

  /**
   * Constructs a <code>ClassificationJobResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJobResponse} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationJobResponse} The populated <code>ClassificationJobResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('inputInfo')) {
        obj['inputInfo'] = ClassificationInputInfo.constructFromObject(data['inputInfo']);
      }
      if (data.hasOwnProperty('jobInfo')) {
        obj['jobInfo'] = JobInfo.constructFromObject(data['jobInfo']);
      }
    }
    return obj;
  }

  /**
   * Original input information
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ClassificationInputInfo} inputInfo
   */
  exports.prototype['inputInfo'] = undefined;
  /**
   * Job info
   * @member {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/JobInfo} jobInfo
   */
  exports.prototype['jobInfo'] = undefined;



  return exports;
}));


