/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationPage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProjectClassificationDocument'), require('./ProjectClassificationPage'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.Inline = factory(root.classification.ApiClient, root.classification.ProjectClassificationDocument, root.classification.ProjectClassificationPage);
  }
}(this, function(ApiClient, ProjectClassificationDocument, ProjectClassificationPage) {
  'use strict';




  /**
   * The Inline model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>Inline</code>.
   * External storage of classification result
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Inline</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/Inline} The populated <code>Inline</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pages')) {
        obj['pages'] = ApiClient.convertToType(data['pages'], [ProjectClassificationPage]);
      }
      if (data.hasOwnProperty('documents')) {
        obj['documents'] = ApiClient.convertToType(data['documents'], [ProjectClassificationDocument]);
      }
    }
    return obj;
  }

  /**
   * A list of pages
   * @member {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationPage>} pages
   */
  exports.prototype['pages'] = undefined;
  /**
   * A list of documents.
   * @member {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument>} documents
   */
  exports.prototype['documents'] = undefined;



  return exports;
}));


