/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient', 'com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProjectClassificationResult'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ProjectClassificationDocument = factory(root.classification.ApiClient, root.classification.ProjectClassificationResult);
  }
}(this, function(ApiClient, ProjectClassificationResult) {
  'use strict';




  /**
   * The ProjectClassificationDocument model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ProjectClassificationDocument</code>.
   * The classification Document
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument
   * @class
   * @param firstPage {Number} First page
   * @param lastPage {Number} Last page
   * @param results {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationResult>} A list of classification results
   */
  var exports = function(firstPage, lastPage, results) {
    var _this = this;

    _this['firstPage'] = firstPage;
    _this['lastPage'] = lastPage;
    _this['results'] = results;
  };

  /**
   * Constructs a <code>ProjectClassificationDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationDocument} The populated <code>ProjectClassificationDocument</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('firstPage')) {
        obj['firstPage'] = ApiClient.convertToType(data['firstPage'], 'Number');
      }
      if (data.hasOwnProperty('lastPage')) {
        obj['lastPage'] = ApiClient.convertToType(data['lastPage'], 'Number');
      }
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [ProjectClassificationResult]);
      }
    }
    return obj;
  }

  /**
   * First page
   * @member {Number} firstPage
   */
  exports.prototype['firstPage'] = undefined;
  /**
   * Last page
   * @member {Number} lastPage
   */
  exports.prototype['lastPage'] = undefined;
  /**
   * A list of classification results
   * @member {Array.<module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationResult>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


