/**
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.classification.handler/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.classification) {
      root.classification = {};
    }
    root.classification.ProjectClassificationClassifierFeature = factory(root.classification.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProjectClassificationClassifierFeature model module.
   * @module com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationClassifierFeature
   * @version 0.3.2
   */

  /**
   * Constructs a new <code>ProjectClassificationClassifierFeature</code>.
   * Classifier feature
   * @alias module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationClassifierFeature
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ProjectClassificationClassifierFeature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationClassifierFeature} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.classification.handler/com.sphereon.sdk.classification.model/ProjectClassificationClassifierFeature} The populated <code>ProjectClassificationClassifierFeature</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'Number');
      }
      if (data.hasOwnProperty('className')) {
        obj['className'] = ApiClient.convertToType(data['className'], 'String');
      }
    }
    return obj;
  }

  /**
   * Score
   * @member {Number} score
   */
  exports.prototype['score'] = undefined;
  /**
   * @member {String} className
   */
  exports.prototype['className'] = undefined;



  return exports;
}));


