/* 
 * Classification API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Classification.Model
{
    /// <summary>
    /// The classification job. Has access to the job settings as well as ocr engine tasks
    /// </summary>
    [DataContract]
    public partial class ClassificationJobResponse :  IEquatable<ClassificationJobResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassificationJobResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClassificationJobResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassificationJobResponse" /> class.
        /// </summary>
        /// <param name="JobInfo">Job info (required).</param>
        /// <param name="InputStreamLocations">The input files. Currently supported inputStreamLocations are: images, pdf- and text files (required).</param>
        public ClassificationJobResponse(JobInfo JobInfo = null, List<StreamLocation> InputStreamLocations = null)
        {
            // to ensure "JobInfo" is required (not null)
            if (JobInfo == null)
            {
                throw new InvalidDataException("JobInfo is a required property for ClassificationJobResponse and cannot be null");
            }
            else
            {
                this.JobInfo = JobInfo;
            }
            // to ensure "InputStreamLocations" is required (not null)
            if (InputStreamLocations == null)
            {
                throw new InvalidDataException("InputStreamLocations is a required property for ClassificationJobResponse and cannot be null");
            }
            else
            {
                this.InputStreamLocations = InputStreamLocations;
            }
        }
        
        /// <summary>
        /// Job info
        /// </summary>
        /// <value>Job info</value>
        [DataMember(Name="jobInfo", EmitDefaultValue=false)]
        public JobInfo JobInfo { get; set; }
        /// <summary>
        /// The input files. Currently supported inputStreamLocations are: images, pdf- and text files
        /// </summary>
        /// <value>The input files. Currently supported inputStreamLocations are: images, pdf- and text files</value>
        [DataMember(Name="inputStreamLocations", EmitDefaultValue=false)]
        public List<StreamLocation> InputStreamLocations { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClassificationJobResponse {\n");
            sb.Append("  JobInfo: ").Append(JobInfo).Append("\n");
            sb.Append("  InputStreamLocations: ").Append(InputStreamLocations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ClassificationJobResponse);
        }

        /// <summary>
        /// Returns true if ClassificationJobResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ClassificationJobResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClassificationJobResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.JobInfo == other.JobInfo ||
                    this.JobInfo != null &&
                    this.JobInfo.Equals(other.JobInfo)
                ) && 
                (
                    this.InputStreamLocations == other.InputStreamLocations ||
                    this.InputStreamLocations != null &&
                    this.InputStreamLocations.SequenceEqual(other.InputStreamLocations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.JobInfo != null)
                    hash = hash * 59 + this.JobInfo.GetHashCode();
                if (this.InputStreamLocations != null)
                    hash = hash * 59 + this.InputStreamLocations.GetHashCode();
                return hash;
            }
        }
    }

}
