/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Classification.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Classification.Model
{
    /// <summary>
    /// The classification job. Has access to the job settings as well as ocr engine tasks
    /// </summary>
    [DataContract]
    public partial class ClassificationJobResponse :  IEquatable<ClassificationJobResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassificationJobResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ClassificationJobResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassificationJobResponse" /> class.
        /// </summary>
        /// <param name="InputInfo">Original input information (required).</param>
        /// <param name="JobInfo">Job info (required).</param>
        public ClassificationJobResponse(ClassificationInputInfo InputInfo = default(ClassificationInputInfo), JobInfo JobInfo = default(JobInfo))
        {
            // to ensure "InputInfo" is required (not null)
            if (InputInfo == null)
            {
                throw new InvalidDataException("InputInfo is a required property for ClassificationJobResponse and cannot be null");
            }
            else
            {
                this.InputInfo = InputInfo;
            }
            // to ensure "JobInfo" is required (not null)
            if (JobInfo == null)
            {
                throw new InvalidDataException("JobInfo is a required property for ClassificationJobResponse and cannot be null");
            }
            else
            {
                this.JobInfo = JobInfo;
            }
        }
        
        /// <summary>
        /// Original input information
        /// </summary>
        /// <value>Original input information</value>
        [DataMember(Name="inputInfo", EmitDefaultValue=false)]
        public ClassificationInputInfo InputInfo { get; set; }

        /// <summary>
        /// Job info
        /// </summary>
        /// <value>Job info</value>
        [DataMember(Name="jobInfo", EmitDefaultValue=false)]
        public JobInfo JobInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ClassificationJobResponse {\n");
            sb.Append("  InputInfo: ").Append(InputInfo).Append("\n");
            sb.Append("  JobInfo: ").Append(JobInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ClassificationJobResponse);
        }

        /// <summary>
        /// Returns true if ClassificationJobResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ClassificationJobResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ClassificationJobResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.InputInfo == other.InputInfo ||
                    this.InputInfo != null &&
                    this.InputInfo.Equals(other.InputInfo)
                ) && 
                (
                    this.JobInfo == other.JobInfo ||
                    this.JobInfo != null &&
                    this.JobInfo.Equals(other.JobInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.InputInfo != null)
                    hash = hash * 59 + this.InputInfo.GetHashCode();
                if (this.JobInfo != null)
                    hash = hash * 59 + this.JobInfo.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
