/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Sphereon.SDK.Classification.Client.SwaggerDateConverter;

namespace Sphereon.SDK.Classification.Model
{
    /// <summary>
    /// Project settings
    /// </summary>
    [DataContract]
    public partial class ProjectSettings :  IEquatable<ProjectSettings>, IValidatableObject
    {
        /// <summary>
        /// Engine
        /// </summary>
        /// <value>Engine</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EngineEnum
        {
            
            /// <summary>
            /// Enum PREMIUM for "PREMIUM"
            /// </summary>
            [EnumMember(Value = "PREMIUM")]
            PREMIUM
        }

        /// <summary>
        /// Engine
        /// </summary>
        /// <value>Engine</value>
        [DataMember(Name="engine", EmitDefaultValue=false)]
        public EngineEnum? Engine { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectSettings" /> class.
        /// </summary>
        /// <param name="ProjectStreamLocations">Project stream locations (required).</param>
        /// <param name="Engine">Engine (required).</param>
        /// <param name="Description">Project description (required).</param>
        /// <param name="ProjectName">Project name (required).</param>
        /// <param name="ProjectStorageLocation">Project Files storage location (required).</param>
        /// <param name="ProjectId">ProjectId.</param>
        public ProjectSettings(List<StreamLocation> ProjectStreamLocations = default(List<StreamLocation>), EngineEnum? Engine = default(EngineEnum?), string Description = default(string), string ProjectName = default(string), StorageLocation ProjectStorageLocation = default(StorageLocation), string ProjectId = default(string))
        {
            // to ensure "ProjectStreamLocations" is required (not null)
            if (ProjectStreamLocations == null)
            {
                throw new InvalidDataException("ProjectStreamLocations is a required property for ProjectSettings and cannot be null");
            }
            else
            {
                this.ProjectStreamLocations = ProjectStreamLocations;
            }
            // to ensure "Engine" is required (not null)
            if (Engine == null)
            {
                throw new InvalidDataException("Engine is a required property for ProjectSettings and cannot be null");
            }
            else
            {
                this.Engine = Engine;
            }
            // to ensure "Description" is required (not null)
            if (Description == null)
            {
                throw new InvalidDataException("Description is a required property for ProjectSettings and cannot be null");
            }
            else
            {
                this.Description = Description;
            }
            // to ensure "ProjectName" is required (not null)
            if (ProjectName == null)
            {
                throw new InvalidDataException("ProjectName is a required property for ProjectSettings and cannot be null");
            }
            else
            {
                this.ProjectName = ProjectName;
            }
            // to ensure "ProjectStorageLocation" is required (not null)
            if (ProjectStorageLocation == null)
            {
                throw new InvalidDataException("ProjectStorageLocation is a required property for ProjectSettings and cannot be null");
            }
            else
            {
                this.ProjectStorageLocation = ProjectStorageLocation;
            }
            this.ProjectId = ProjectId;
        }
        
        /// <summary>
        /// Project stream locations
        /// </summary>
        /// <value>Project stream locations</value>
        [DataMember(Name="projectStreamLocations", EmitDefaultValue=false)]
        public List<StreamLocation> ProjectStreamLocations { get; set; }


        /// <summary>
        /// Project description
        /// </summary>
        /// <value>Project description</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Project name
        /// </summary>
        /// <value>Project name</value>
        [DataMember(Name="projectName", EmitDefaultValue=false)]
        public string ProjectName { get; set; }

        /// <summary>
        /// Project Files storage location
        /// </summary>
        /// <value>Project Files storage location</value>
        [DataMember(Name="projectStorageLocation", EmitDefaultValue=false)]
        public StorageLocation ProjectStorageLocation { get; set; }

        /// <summary>
        /// Gets or Sets ProjectId
        /// </summary>
        [DataMember(Name="projectId", EmitDefaultValue=false)]
        public string ProjectId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProjectSettings {\n");
            sb.Append("  ProjectStreamLocations: ").Append(ProjectStreamLocations).Append("\n");
            sb.Append("  Engine: ").Append(Engine).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ProjectName: ").Append(ProjectName).Append("\n");
            sb.Append("  ProjectStorageLocation: ").Append(ProjectStorageLocation).Append("\n");
            sb.Append("  ProjectId: ").Append(ProjectId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProjectSettings);
        }

        /// <summary>
        /// Returns true if ProjectSettings instances are equal
        /// </summary>
        /// <param name="other">Instance of ProjectSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProjectSettings other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ProjectStreamLocations == other.ProjectStreamLocations ||
                    this.ProjectStreamLocations != null &&
                    this.ProjectStreamLocations.SequenceEqual(other.ProjectStreamLocations)
                ) && 
                (
                    this.Engine == other.Engine ||
                    this.Engine != null &&
                    this.Engine.Equals(other.Engine)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.ProjectName == other.ProjectName ||
                    this.ProjectName != null &&
                    this.ProjectName.Equals(other.ProjectName)
                ) && 
                (
                    this.ProjectStorageLocation == other.ProjectStorageLocation ||
                    this.ProjectStorageLocation != null &&
                    this.ProjectStorageLocation.Equals(other.ProjectStorageLocation)
                ) && 
                (
                    this.ProjectId == other.ProjectId ||
                    this.ProjectId != null &&
                    this.ProjectId.Equals(other.ProjectId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ProjectStreamLocations != null)
                    hash = hash * 59 + this.ProjectStreamLocations.GetHashCode();
                if (this.Engine != null)
                    hash = hash * 59 + this.Engine.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.ProjectName != null)
                    hash = hash * 59 + this.ProjectName.GetHashCode();
                if (this.ProjectStorageLocation != null)
                    hash = hash * 59 + this.ProjectStorageLocation.GetHashCode();
                if (this.ProjectId != null)
                    hash = hash * 59 + this.ProjectId.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
