/* 
 * Classification API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Classification.Model
{
    /// <summary>
    /// The result location of a stream
    /// </summary>
    [DataContract]
    public partial class StreamResponse :  IEquatable<StreamResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StreamResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamResponse" /> class.
        /// </summary>
        /// <param name="StreamLocation">The actual location of the stream (required).</param>
        public StreamResponse(StreamLocation StreamLocation = null)
        {
            // to ensure "StreamLocation" is required (not null)
            if (StreamLocation == null)
            {
                throw new InvalidDataException("StreamLocation is a required property for StreamResponse and cannot be null");
            }
            else
            {
                this.StreamLocation = StreamLocation;
            }
        }
        
        /// <summary>
        /// The actual location of the stream
        /// </summary>
        /// <value>The actual location of the stream</value>
        [DataMember(Name="streamLocation", EmitDefaultValue=false)]
        public StreamLocation StreamLocation { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamResponse {\n");
            sb.Append("  StreamLocation: ").Append(StreamLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StreamResponse);
        }

        /// <summary>
        /// Returns true if StreamResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of StreamResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.StreamLocation == other.StreamLocation ||
                    this.StreamLocation != null &&
                    this.StreamLocation.Equals(other.StreamLocation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.StreamLocation != null)
                    hash = hash * 59 + this.StreamLocation.GetHashCode();
                return hash;
            }
        }
    }

}
