/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing ClassificationProjectInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClassificationProjectInfoTests
    {
        // TODO uncomment below to declare an instance variable for ClassificationProjectInfo
        //private ClassificationProjectInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClassificationProjectInfo
            //instance = new ClassificationProjectInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClassificationProjectInfo
        /// </summary>
        [Test]
        public void ClassificationProjectInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClassificationProjectInfo
            //Assert.IsInstanceOfType<ClassificationProjectInfo> (instance, "variable 'instance' is a ClassificationProjectInfo");
        }

        /// <summary>
        /// Test the property 'ProjectStreamLocations'
        /// </summary>
        [Test]
        public void ProjectStreamLocationsTest()
        {
            // TODO unit test for the property 'ProjectStreamLocations'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }

    }

}
