/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing ClassificationProjectResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClassificationProjectResultTests
    {
        // TODO uncomment below to declare an instance variable for ClassificationProjectResult
        //private ClassificationProjectResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClassificationProjectResult
            //instance = new ClassificationProjectResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClassificationProjectResult
        /// </summary>
        [Test]
        public void ClassificationProjectResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ClassificationProjectResult
            //Assert.IsInstanceOfType<ClassificationProjectResult> (instance, "variable 'instance' is a ClassificationProjectResult");
        }

        /// <summary>
        /// Test the property 'ProjectInfo'
        /// </summary>
        [Test]
        public void ProjectInfoTest()
        {
            // TODO unit test for the property 'ProjectInfo'
        }
        /// <summary>
        /// Test the property 'Inline'
        /// </summary>
        [Test]
        public void InlineTest()
        {
            // TODO unit test for the property 'Inline'
        }
        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Test]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }
        /// <summary>
        /// Test the property 'ClassificationType'
        /// </summary>
        [Test]
        public void ClassificationTypeTest()
        {
            // TODO unit test for the property 'ClassificationType'
        }
        /// <summary>
        /// Test the property 'ResultType'
        /// </summary>
        [Test]
        public void ResultTypeTest()
        {
            // TODO unit test for the property 'ResultType'
        }

    }

}
