/* 
 * Classification API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing JobInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobInfoTests
    {
        // TODO uncomment below to declare an instance variable for JobInfo
        //private JobInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JobInfo
            //instance = new JobInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobInfo
        /// </summary>
        [Test]
        public void JobInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JobInfo
            //Assert.IsInstanceOfType<JobInfo> (instance, "variable 'instance' is a JobInfo");
        }

        /// <summary>
        /// Test the property 'CompletionTime'
        /// </summary>
        [Test]
        public void CompletionTimeTest()
        {
            // TODO unit test for the property 'CompletionTime'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Test]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Test]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }
        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Test]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }
        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Test]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }
        /// <summary>
        /// Test the property 'QueueTime'
        /// </summary>
        [Test]
        public void QueueTimeTest()
        {
            // TODO unit test for the property 'QueueTime'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
