/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing Lifecycle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LifecycleTests
    {
        // TODO uncomment below to declare an instance variable for Lifecycle
        //private Lifecycle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Lifecycle
            //instance = new Lifecycle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Lifecycle
        /// </summary>
        [Test]
        public void LifecycleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Lifecycle
            //Assert.IsInstanceOfType<Lifecycle> (instance, "variable 'instance' is a Lifecycle");
        }

        /// <summary>
        /// Test the property 'ActionTime'
        /// </summary>
        [Test]
        public void ActionTimeTest()
        {
            // TODO unit test for the property 'ActionTime'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
