/* 
 * Classification API
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing ProjectClassificationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectClassificationResultTests
    {
        // TODO uncomment below to declare an instance variable for ProjectClassificationResult
        //private ProjectClassificationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectClassificationResult
            //instance = new ProjectClassificationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectClassificationResult
        /// </summary>
        [Test]
        public void ProjectClassificationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProjectClassificationResult
            //Assert.IsInstanceOfType<ProjectClassificationResult> (instance, "variable 'instance' is a ProjectClassificationResult");
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Test]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }

    }

}
