/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing ProjectClassificationClassifierFeature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectClassificationClassifierFeatureTests
    {
        // TODO uncomment below to declare an instance variable for ProjectClassificationClassifierFeature
        //private ProjectClassificationClassifierFeature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProjectClassificationClassifierFeature
            //instance = new ProjectClassificationClassifierFeature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProjectClassificationClassifierFeature
        /// </summary>
        [Test]
        public void ProjectClassificationClassifierFeatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProjectClassificationClassifierFeature
            //Assert.IsInstanceOfType<ProjectClassificationClassifierFeature> (instance, "variable 'instance' is a ProjectClassificationClassifierFeature");
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Test]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }

    }

}
