/* 
 * Classification API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Classification.Api;
using Sphereon.SDK.Classification.Model;
using Sphereon.SDK.Classification.Client;
using System.Reflection;

namespace Sphereon.SDK.Classification.Test
{
    /// <summary>
    ///  Class for testing Stream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamTests
    {
        // TODO uncomment below to declare an instance variable for Stream
        //private Stream instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Stream
            //instance = new Stream();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Stream
        /// </summary>
        [Test]
        public void StreamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Stream
            //Assert.IsInstanceOfType<Stream> (instance, "variable 'instance' is a Stream");
        }

        /// <summary>
        /// Test the property 'StreamLocation'
        /// </summary>
        [Test]
        public void StreamLocationTest()
        {
            // TODO unit test for the property 'StreamLocation'
        }

    }

}
