/*
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.classification.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sphereon.sdk.classification.model.SummaryItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The classification job. Has access to the job settings as well as ocr engine tasks
 */
@ApiModel(description = "The classification job. Has access to the job settings as well as ocr engine tasks")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T13:02:31.104+02:00")
public class ClassificationSummary {
  @SerializedName("items")
  private List<SummaryItem> items = new ArrayList<SummaryItem>();

  public ClassificationSummary items(List<SummaryItem> items) {
    this.items = items;
    return this;
  }

  public ClassificationSummary addItemsItem(SummaryItem itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Classification job summary items
   * @return items
  **/
  @ApiModelProperty(required = true, value = "Classification job summary items")
  public List<SummaryItem> getItems() {
    return items;
  }

  public void setItems(List<SummaryItem> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationSummary classificationSummary = (ClassificationSummary) o;
    return Objects.equals(this.items, classificationSummary.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationSummary {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

