/*
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.classification.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sphereon.sdk.classification.model.ClassificationResult;
import com.sphereon.sdk.classification.model.ClassificationSummary;
import com.sphereon.sdk.classification.model.JobInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The Classification response
 */
@ApiModel(description = "The Classification response")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T13:02:31.104+02:00")
public class ClassificationResponse {
  @SerializedName("classificationResult")
  private ClassificationResult classificationResult = null;

  @SerializedName("summary")
  private ClassificationSummary summary = null;

  /**
   * Gets or Sets detailLevels
   */
  @JsonAdapter(DetailLevelsEnum.Adapter.class)
  public enum DetailLevelsEnum {
    SUMMARY("SUMMARY"),
    
    DEFAULT("DEFAULT"),
    
    RAW("RAW");

    private String value;

    DetailLevelsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DetailLevelsEnum fromValue(String text) {
      for (DetailLevelsEnum b : DetailLevelsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DetailLevelsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DetailLevelsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DetailLevelsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DetailLevelsEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("detailLevels")
  private List<DetailLevelsEnum> detailLevels = new ArrayList<DetailLevelsEnum>();

  @SerializedName("jobInfo")
  private JobInfo jobInfo = null;

  public ClassificationResponse classificationResult(ClassificationResult classificationResult) {
    this.classificationResult = classificationResult;
    return this;
  }

   /**
   * Classification results
   * @return classificationResult
  **/
  @ApiModelProperty(value = "Classification results")
  public ClassificationResult getClassificationResult() {
    return classificationResult;
  }

  public void setClassificationResult(ClassificationResult classificationResult) {
    this.classificationResult = classificationResult;
  }

  public ClassificationResponse summary(ClassificationSummary summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Classification job summary
   * @return summary
  **/
  @ApiModelProperty(value = "Classification job summary")
  public ClassificationSummary getSummary() {
    return summary;
  }

  public void setSummary(ClassificationSummary summary) {
    this.summary = summary;
  }

  public ClassificationResponse detailLevels(List<DetailLevelsEnum> detailLevels) {
    this.detailLevels = detailLevels;
    return this;
  }

  public ClassificationResponse addDetailLevelsItem(DetailLevelsEnum detailLevelsItem) {
    this.detailLevels.add(detailLevelsItem);
    return this;
  }

   /**
   * Level of detail for the results
   * @return detailLevels
  **/
  @ApiModelProperty(required = true, value = "Level of detail for the results")
  public List<DetailLevelsEnum> getDetailLevels() {
    return detailLevels;
  }

  public void setDetailLevels(List<DetailLevelsEnum> detailLevels) {
    this.detailLevels = detailLevels;
  }

  public ClassificationResponse jobInfo(JobInfo jobInfo) {
    this.jobInfo = jobInfo;
    return this;
  }

   /**
   * Job info
   * @return jobInfo
  **/
  @ApiModelProperty(required = true, value = "Job info")
  public JobInfo getJobInfo() {
    return jobInfo;
  }

  public void setJobInfo(JobInfo jobInfo) {
    this.jobInfo = jobInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationResponse classificationResponse = (ClassificationResponse) o;
    return Objects.equals(this.classificationResult, classificationResponse.classificationResult) &&
        Objects.equals(this.summary, classificationResponse.summary) &&
        Objects.equals(this.detailLevels, classificationResponse.detailLevels) &&
        Objects.equals(this.jobInfo, classificationResponse.jobInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classificationResult, summary, detailLevels, jobInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationResponse {\n");
    
    sb.append("    classificationResult: ").append(toIndentedString(classificationResult)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    detailLevels: ").append(toIndentedString(detailLevels)).append("\n");
    sb.append("    jobInfo: ").append(toIndentedString(jobInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

