/*
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.classification.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sphereon.sdk.classification.model.ClassificationInputInfo;
import com.sphereon.sdk.classification.model.ClassificationProjectResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Document to be classified
 */
@ApiModel(description = "Document to be classified")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T13:02:31.104+02:00")
public class ClassificationResultItem {
  @SerializedName("inputInfo")
  private ClassificationInputInfo inputInfo = null;

  @SerializedName("results")
  private List<ClassificationProjectResult> results = null;

  public ClassificationResultItem inputInfo(ClassificationInputInfo inputInfo) {
    this.inputInfo = inputInfo;
    return this;
  }

   /**
   * Original input information
   * @return inputInfo
  **/
  @ApiModelProperty(required = true, value = "Original input information")
  public ClassificationInputInfo getInputInfo() {
    return inputInfo;
  }

  public void setInputInfo(ClassificationInputInfo inputInfo) {
    this.inputInfo = inputInfo;
  }

  public ClassificationResultItem results(List<ClassificationProjectResult> results) {
    this.results = results;
    return this;
  }

  public ClassificationResultItem addResultsItem(ClassificationProjectResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<ClassificationProjectResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Classification results for a document per project
   * @return results
  **/
  @ApiModelProperty(value = "Classification results for a document per project")
  public List<ClassificationProjectResult> getResults() {
    return results;
  }

  public void setResults(List<ClassificationProjectResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationResultItem classificationResultItem = (ClassificationResultItem) o;
    return Objects.equals(this.inputInfo, classificationResultItem.inputInfo) &&
        Objects.equals(this.results, classificationResultItem.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputInfo, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationResultItem {\n");
    
    sb.append("    inputInfo: ").append(toIndentedString(inputInfo)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

