/**
 * Classification API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.classification.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.sphereon.sdk.classification.model.ProjectClassificationWord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * Text line
 */
@ApiModel(description = "Text line")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-28T08:34:28.559+02:00")
public class ProjectClassificationTextLine   {
  @SerializedName("top")
  private Integer top = null;

  @SerializedName("left")
  private Integer left = null;

  @SerializedName("bottom")
  private Integer bottom = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("words")
  private List<ProjectClassificationWord> words = new ArrayList<ProjectClassificationWord>();

  @SerializedName("right")
  private Integer right = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("height")
  private Integer height = null;

  public ProjectClassificationTextLine top(Integer top) {
    this.top = top;
    return this;
  }

   /**
   * The top pixel coordinate of the text line
   * @return top
  **/
  @ApiModelProperty(example = "null", value = "The top pixel coordinate of the text line")
  public Integer getTop() {
    return top;
  }

  public void setTop(Integer top) {
    this.top = top;
  }

  public ProjectClassificationTextLine left(Integer left) {
    this.left = left;
    return this;
  }

   /**
   * The left pixel coordinate of the text line
   * @return left
  **/
  @ApiModelProperty(example = "null", value = "The left pixel coordinate of the text line")
  public Integer getLeft() {
    return left;
  }

  public void setLeft(Integer left) {
    this.left = left;
  }

  public ProjectClassificationTextLine bottom(Integer bottom) {
    this.bottom = bottom;
    return this;
  }

   /**
   * The bottom pixel coordinate of the text line
   * @return bottom
  **/
  @ApiModelProperty(example = "null", value = "The bottom pixel coordinate of the text line")
  public Integer getBottom() {
    return bottom;
  }

  public void setBottom(Integer bottom) {
    this.bottom = bottom;
  }

  public ProjectClassificationTextLine width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * The width of the text line in pixel coordinate
   * @return width
  **/
  @ApiModelProperty(example = "null", value = "The width of the text line in pixel coordinate")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public ProjectClassificationTextLine words(List<ProjectClassificationWord> words) {
    this.words = words;
    return this;
  }

  public ProjectClassificationTextLine addWordsItem(ProjectClassificationWord wordsItem) {
    this.words.add(wordsItem);
    return this;
  }

   /**
   * All words of this text line
   * @return words
  **/
  @ApiModelProperty(example = "null", value = "All words of this text line")
  public List<ProjectClassificationWord> getWords() {
    return words;
  }

  public void setWords(List<ProjectClassificationWord> words) {
    this.words = words;
  }

  public ProjectClassificationTextLine right(Integer right) {
    this.right = right;
    return this;
  }

   /**
   * The right pixel coordinate of the text line
   * @return right
  **/
  @ApiModelProperty(example = "null", value = "The right pixel coordinate of the text line")
  public Integer getRight() {
    return right;
  }

  public void setRight(Integer right) {
    this.right = right;
  }

  public ProjectClassificationTextLine text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The text of this line from the words
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "The text of this line from the words")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ProjectClassificationTextLine height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The height of the text line in pixel coordinate
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "The height of the text line in pixel coordinate")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectClassificationTextLine projectClassificationTextLine = (ProjectClassificationTextLine) o;
    return Objects.equals(this.top, projectClassificationTextLine.top) &&
        Objects.equals(this.left, projectClassificationTextLine.left) &&
        Objects.equals(this.bottom, projectClassificationTextLine.bottom) &&
        Objects.equals(this.width, projectClassificationTextLine.width) &&
        Objects.equals(this.words, projectClassificationTextLine.words) &&
        Objects.equals(this.right, projectClassificationTextLine.right) &&
        Objects.equals(this.text, projectClassificationTextLine.text) &&
        Objects.equals(this.height, projectClassificationTextLine.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(top, left, bottom, width, words, right, text, height);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectClassificationTextLine {\n");
    
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    bottom: ").append(toIndentedString(bottom)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    words: ").append(toIndentedString(words)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

