/*
 * Classification API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.classification.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Word of text line
 */
@ApiModel(description = "Word of text line")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-17T13:02:31.104+02:00")
public class ProjectClassificationWord {
  @SerializedName("top")
  private Integer top = null;

  @SerializedName("left")
  private Integer left = null;

  @SerializedName("bottom")
  private Integer bottom = null;

  @SerializedName("width")
  private Integer width = null;

  @SerializedName("right")
  private Integer right = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("height")
  private Integer height = null;

  public ProjectClassificationWord top(Integer top) {
    this.top = top;
    return this;
  }

   /**
   * The top pixel coordinate of the text line
   * @return top
  **/
  @ApiModelProperty(value = "The top pixel coordinate of the text line")
  public Integer getTop() {
    return top;
  }

  public void setTop(Integer top) {
    this.top = top;
  }

  public ProjectClassificationWord left(Integer left) {
    this.left = left;
    return this;
  }

   /**
   * The left pixel coordinate of the text line
   * @return left
  **/
  @ApiModelProperty(value = "The left pixel coordinate of the text line")
  public Integer getLeft() {
    return left;
  }

  public void setLeft(Integer left) {
    this.left = left;
  }

  public ProjectClassificationWord bottom(Integer bottom) {
    this.bottom = bottom;
    return this;
  }

   /**
   * The bottom pixel coordinate of the text line
   * @return bottom
  **/
  @ApiModelProperty(value = "The bottom pixel coordinate of the text line")
  public Integer getBottom() {
    return bottom;
  }

  public void setBottom(Integer bottom) {
    this.bottom = bottom;
  }

  public ProjectClassificationWord width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * The width of the text line in pixel coordinate
   * @return width
  **/
  @ApiModelProperty(value = "The width of the text line in pixel coordinate")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public ProjectClassificationWord right(Integer right) {
    this.right = right;
    return this;
  }

   /**
   * The right pixel coordinate of the text line
   * @return right
  **/
  @ApiModelProperty(value = "The right pixel coordinate of the text line")
  public Integer getRight() {
    return right;
  }

  public void setRight(Integer right) {
    this.right = right;
  }

  public ProjectClassificationWord text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The text of the word
   * @return text
  **/
  @ApiModelProperty(value = "The text of the word")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ProjectClassificationWord height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The height of the text line in pixel coordinate
   * @return height
  **/
  @ApiModelProperty(value = "The height of the text line in pixel coordinate")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectClassificationWord projectClassificationWord = (ProjectClassificationWord) o;
    return Objects.equals(this.top, projectClassificationWord.top) &&
        Objects.equals(this.left, projectClassificationWord.left) &&
        Objects.equals(this.bottom, projectClassificationWord.bottom) &&
        Objects.equals(this.width, projectClassificationWord.width) &&
        Objects.equals(this.right, projectClassificationWord.right) &&
        Objects.equals(this.text, projectClassificationWord.text) &&
        Objects.equals(this.height, projectClassificationWord.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(top, left, bottom, width, right, text, height);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectClassificationWord {\n");
    
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    bottom: ").append(toIndentedString(bottom)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

